omgovich/react-colorful

demo/src/index.js
package.json
src/components/ColorPicker.js
src/components/Hue.js
src/components/Saturation.js
src/utils.js
tests/utils.js

Replaced `tinycolor2` with `color-fns`.
`color-fns` is modular and tree-shakable (inspired by date-fns).
```js
// 3,7 KB (1,6 gzipped)
import { rgbToHsv, hexToRgb, rgbToHex, hsvToRgb, formatHex } from "color-fns";
```
vs
```js
// 15 KB (5,3 gzipped)
import tinycolor from "tinycolor2";
```

Migrate to color-fns

---

package.json
src/components/ColorPicker.js
src/components/Hue.js
src/components/Saturation.js
src/utils.js
tests/utils.js

Migrate from `color-fns` to [`@swiftcarrot/color-fns`](https://github.com/swiftcarrot/color-fns) which:
- well supported by authors (~2 updates per month).
- has better test coverage.
- 1,6 times lighter:
- Uses a more popular HSV object structure (`{h,s,v}` instead of `{hue, sat, val, alpha}`).

Migrate to @swiftcarrot/color-fns

---

package.json

The current `prepublish` script which builds the library runs on `npm install` and that seems confusing. Moreover, the `prepublish` seems to be deprecated as of npm@5:
> Deprecation Note: prepublish
>
> Since npm@1.1.71, the npm CLI has run the prepublish script for both
> npm  publish  and npm install, because it's a convenient way to pre-
> pare a package for use (some common use cases are described  in  the
> section  below).   It  has  also turned out to be, in practice, very
> confusing https://github.com/npm/npm/issues/10074.  As of npm@4.0.0,
> a new event has been introduced, prepare, that preserves this exist-
> ing behavior. A new event, prepublishOnly has been added as a  tran-
> sitional  strategy to allow users to avoid the confusing behavior of
> existing npm versions and …

Replace `prepublish` deprecated npm step with `prepublishOnly`

---

ACKNOWLEDGMENTS
src/packages/hex.js
src/utils/formatClassName.js
src/utils/hexToRgb.js
src/utils/hsvToRgb.js
src/utils/rgbToHex.js
src/utils/rgbToHsv.js
tests/components.test.js
tests/utils.test.js

Rewrote few methods and used small tweaks in order to make the HEX color picker bundle lighter.
```
1609 B → 1539 B (–70 B)

Optimizations: Make the default bundle lighter

---

.eslintrc
.gitignore
README.md
demo/src/index.html
demo/src/index.js
demo/src/styles.css
package.json
src/components/HexInput.js
src/packages/HexInput.js
src/utils/validHex.js
tests/__snapshots__/components.test.js.snap
tests/components.test.js
tests/utils.test.js

In case if the user needs to have a text field to type/paste HEX-color, he could import additional `HexInput` component which works well in pair with the picker and costs just 400 bytes:
```js
import ColorPicker from "react-colorful";
import HexInput from 'react-colorful/HexInput';
const YourComponent = () => {
const [color, setColor] = useState("#aabbcc");
return (
<div>
<ColorPicker color={color} onChange={setColor} />
<HexInput color={color} onChange={setColor} />
</div>
);
};
```
This component doesn't have any default styles. It's just an input with proper behavior. The developers could place and tweak this component any way they want.
BTW I noticed that ~33% of the `HexInput`'s bundle size was the spread operator polyfill, so I used `React.createElement("input", Object.assign({}, …

HexInput component

---

build-packages.js

Closes #27
Tarball content:
```
unpacked size: 559.7 → 132.9 kB
total files:   191 → 163 
```

Don't publish sourcemaps to NPM

---

src/components/HexInput.tsx

@RyanChristian4427 I just noticed that it's not allowed to pass the default input tag props (such as `className`, `placeholder`, etc) to `HexInput` component.

TS: Allow to pass another props to HexInput

---

src/hsl.tsx
src/hsv.tsx
src/rgb.tsx
src/types.ts
src/utils/compare.ts

PR is in response to [this comment](https://github.com/omgovich/react-colorful/pull/23#issuecomment-683318037).
This adds HSL, HSV, and RGB as named exports for their respective color pickers, resulting in the following API:
```
import HslColorPicker, { HSL } from 'react-colorful/hsl';
```
This is a major improvement in accessibility over the previous solution:
```
import HslColorPicker from 'react-colorful/hsl';
import { HSL } from 'react-colorful/dist/types';
```
Only a single import statement required.
I also changed our types a bit to remove the indexing on the objects outside of the color object comparator scope. The color object comparator is a bit more verbose and more complicated with its casts but it's an improvement, especially with the types now being exported.

feat: Color object types as named exports

---

README.md

Adding documentation for usage with Preact.
Added a few links for common Preact starting points that will work right out of the box along with documentation on how to use when not using one of those starting points.
I removed "Preact Support" from the roadmap and labeled the Preact section as "Usage with Preact" because it's rather incorrect to say this library supports Preact in any way. It has been the Preact team's work through `preact/compat` that ensures most React libraries (this one included) will work flawlessly in a Preact application. Saying that we support it therefore feels a bit disingenuous as we really didn't do anything ourselves.

docs(readme): Added Preact section

---

.github/workflows/main.yml

Compressed Size Action is a GitHub action that reports changes in the compressed file sizes in PRs. [Source Page](https://github.com/preactjs/compressed-size-action). This will allow you to see, at a glance, whether a PR increases or decreases your bundle size, and by how much. Incredibly useful for a library watching its size like this one. It would catch [regressions like this](https://github.com/omgovich/react-colorful/pull/23#issuecomment-680262792) that would normally require manually checking/comparing of numbers.
As of now, this only runs on a PR, but it is also in the works to support push events. 
Having ran a [quick test here](https://github.com/RyanChristian4427/react-colorful/pull/1) it seems that this may only pick up on changes in a `dist` directory. Will figure out the root …

ci(actions): Adding compressed-size-action

---

demo/src/index.js
src/components/ColorPicker.tsx
src/components/HexInput.tsx
src/hooks/useEventCallback.ts
tests/components.test.js

Hey @omgovich,
I try do my best: 
- now only unique color fires `onChange` callback
- `onChange` callback is saved in ref, so `useCallback` is not required on parent level
- performance is improved

add couple improvements 🙌🏻

---

src/components/common/Interactive.tsx

Fixes #52 
Demo on FireFox (Windows and Linux) throws errors that `TouchEvent` is not defined when attempting to move the picker. The fix is just a check to see if it's defined.

fix: Resolving demo errors on Firefox

---

src/components/common/Interactive.tsx
tests/components.test.js

Fixes #55
The problem happens because sometimes iOS Safari calls `mousedown` and `mouseup` right after short touch interactions.
It seems to me that the browser thinks that it was a click (a combination of `mousedown` and `mouseup`) so it handles these events as well.

Fix: Fast Tap and Release in iOS Safari

---

README.md
package.json
src/components/common/Alpha.tsx
src/components/common/ColorPicker.tsx
src/components/common/Hue.tsx
src/components/common/Interactive.tsx
src/components/common/Saturation.tsx
src/css/styles.css
src/utils/clamp.ts
src/utils/convert.ts
src/utils/limit.ts
tests/__snapshots__/components.test.js.snap
tests/components.test.js
tests/utils.test.js

Accessibility, keyboard support

---

README.md

Would close #39 
This PR adds a subsection to the Preact section of the ReadMe that describes a potential problem that can arise with a Preact TS application and this library (or any React component library that uses `@types/react` for that matter). 
As the [Preact TypeScript template](https://github.com/preactjs-templates/typescript) will throw this error right out-of-the-box I feel that it is important to note, even if not an issue that this library can solve.
As a heavy user of Preact, I love when a library author acknowledges Preact users and notes any potential changes that will need to be made. I figure we can do the same here especially as this is quite an easy fix.
I'm not entirely sure that I love the wording right now, might come back later and make some adjustments or rewrite …

docs(readme): Expounding upon Preact + TS set up

---

src/components/common/Interactive.tsx

Updated `isTouch` with user defined type guard, which makes the code a bit cleaner by removing extra type cast.

refactor: simplify touch event type check

---

package.json
src/components/common/Alpha.tsx
src/components/common/Hue.tsx
src/components/common/Pointer.tsx
src/components/common/Saturation.tsx
src/css/styles.css
src/css/styles.css.d.ts
tests/__snapshots__/components.test.js.snap

Fixes #73 
Safari is a new IE...
Safari 14 doesn't work properly with `currentColor`, so I had to replace a pseudo-element that has `background-color: currentColor` with a regular `div` having `background-color`.
@rschristian Could you take a look?

Fix pointer displaying in Safari 14

---

README.md
src/components/HsvaColorPicker.tsx
src/components/common/Alpha.tsx
src/components/common/Hue.tsx
src/components/common/Saturation.tsx
src/utils/convert.ts
src/utils/round.ts
tests/components.test.js
tests/utils.test.js

Closes #76
All color models except HEX and RGB are awkward to use because output values have too many digits after the decimal point.
The internal value is still super accurate (like `{ h: 1.23456789, s: 2.3456789, v: 3.4567, a: 0.9999999 }`).
Why? To keep the movement of pointers super smooth even when the picker size is 1000x1000.
This PR makes all output values rounded to the nearest integer.
Only alpha value has 2 digits to appear after the decimal point.
```js
hsl(200.4326236, 25.124125%, 32.121212%, 0.6666666) // will be impossible to get after merging this PR
hsl(200, 25%, 32%, 0.67) // that's what we going to return
```
@rschristian @molefrog Could I ask you to review the PR?

Round output values

---

src/components/common/Interactive.tsx
src/hooks/useIsomorphicLayoutEffect.ts

Closes #94
> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
The hack is copied from `react-redux` repo.

Get rid of `useLayoutEffect` warning when using on the server

---

.github/workflows/node.yml

Currently the CI isn't running against PRs, so you can't see if they fail linting/building/testing
I imagine you'd want that enabled, as it'd catch the simple errors (like the multiple linting ones that I just had to fix, whoops)

ci: Running lint/build/test on PR too

---

package.json

add names so size-limit shows component name not `dist/index.module.js` for each check
```
HexColorPicker
Size limit: 3 KB
Size:       2.66 KB with all dependencies, minified and gzipped
HslColorPicker
Size limit: 3 KB
Size:       2.38 KB with all dependencies, minified and gzipped
HslaColorPicker
Size limit: 3 KB
Size:       2.47 KB with all dependencies, minified and gzipped
HslStringColorPicker
Size limit: 3 KB
Size:       2.46 KB with all dependencies, minified and gzipped
HslaStringColorPicker
Size limit: 3 KB
Size:       2.58 KB with all dependencies, minified and gzipped
```

tune size-limit config

---

src/components/common/AlphaColorPicker.tsx
src/components/common/ColorPicker.tsx
src/types.ts
tests/__snapshots__/components.test.js.snap
tests/components.test.js

I was working on some demos recently and noticed that it's not possible to add `id` or another HTML attribute to the root div. Also the picker does not support native DOM events that a regular `div` does (e.g. `onMouseEnter`).

HTML attributes support

---

package.json

See [this Twitter discussion](https://twitter.com/Omgovich/status/1379904772170465280).
Added `"default"` key to the export map pointing to the ESM file as described in the [Webpack docs](https://webpack.js.org/guides/package-exports/#conditional-syntax).

Add fallback to the exports map

---

src/utils/convert.ts
tests/utils.test.js

Library's parsers were improved to support more CSS color formats and units.
```js
// percentage syntax
"rgb(100% 50% 25%)"
// deg, grad, rad, turn units
"hsla(100grad, 50%, 50%)"
"hsla(0.25turn, 50%, 50%)"
// modern slash-syntax is supported
"rgba(100% 50% 25% / 99%)"
"hsla(90 50% 50% / 10%)"
// optional leading zero is now supported
"hsla(.25turn, .9%, .5%, .25)"
```

Support modern CSS color notations

---

package-lock.json
src/components/common/Interactive.tsx
src/hooks/useEventCallback.ts
tests/components.test.js

This diff makes the runtime faster and the library size smaller
|Before|After|
|---|---|
| ![image](https://user-images.githubusercontent.com/1178825/127752345-e76fc4b1-780e-4746-9a81-3b3c1e885f5c.png) | ![image](https://user-images.githubusercontent.com/1178825/128600170-5d286787-af47-409f-ad9d-997ef59a1b1d.png) |
| ![image](https://user-images.githubusercontent.com/1178825/127752357-39d94d53-7395-4d91-a361-80a788f72e4c.png) | ![image](https://user-images.githubusercontent.com/1178825/128600184-e9b3b1a7-504e-4b7e-be8b-b9c5dab09331.png) |
As we get rid of `useEffect` calls, it saves time in runtime. 
It also prevents us from the memory leak and potential errors
The behaviour isn't changed:
https://user-images.githubusercontent.com/1178825/128600229-9f30f0ae-5cf6-4c31-ae57-62cb17e3bdce.mov

Optimize hooks, reduce library size and get rid of edge case errors and memory leaks

---

README.md

Just noticed two very minor errors in the README.
In terms of "straightforward", if you're interested, here are two links that helpfully define or describe the word:
- https://dictionary.cambridge.org/dictionary/english/straightforward
- https://ell.stackexchange.com/a/4573

Fix minor spelling and grammar errors in README

---

src/components/HexColorInput.tsx
src/utils/convert.ts

Removes the `substr` method, as it's deprecated:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr

Use `substring` instead of deprecated `substr`.

---

README.md
demo/src/components/DevTools.tsx
demo/src/components/PickerPreview.tsx
src/components/HexAlphaColorPicker.tsx
src/components/HexColorPicker.tsx
src/index.ts
src/utils/convert.ts
tests/components.test.js

Closes #161
Adding new `HexAlphaColorPicker` component to work with "#rrggbbaa" and "#rgba" color formats.

Add `HexAlphaColorPicker`
