omgovich/react-colorful

package.json
=> fix: setup jsx pragma for react

README.md
- Added a benchmark of popular color picker components.
- Explained why people should consider using react-colorful.
=> Add simple benchmark

demo/src/index.js, demo/src/styles.css
Setting the color on the entire body element will guarantee that the color is applied to out of borders area. Just in case someone wants to scroll the page, it just feels cleaner.
=> Demo: set the background color on the whole body

README.md
@molefrog Could you take a look?
=> Readme for V2

build-packages.js, package.json
Hey, @RyanChristian4427 👋 Check this out.
I took your concept from #25, but keeps packages ignored by Git.
Also, I made the building process parallel by `Promise.all(...)`
=> Building process improvement

README.md
Added documentation for TS support as [mentioned here](https://github.com/omgovich/react-colorful/pull/33#issuecomment-683333130).
=> docs(readme): Creating TS support section

src/components/common/Interactive.tsx
@RyanChristian4427 Could you take a look?
=> Improve `Interactive` internal typing

demo/src/components/Icon.tsx, demo/src/css/styles.css, demo/src/css/styles.css.d.ts, demo/src/hooks/useStargazerCount.ts, demo/src/index.tsx
=> Demo: display stargazer count

demo/src/css/styles.css, demo/src/hooks/useStargazerCount.ts, demo/src/index.tsx
=> Display an alpha color picker on the demo page

README.md
Not sure about the header though. Alternatives:
- "Other Frameworks"
- "Ports"
=> Add a README section with project ports

README.md, demo/src/hooks/useStargazerCount.ts, demo/src/index.html, src/components/common/Alpha.tsx
=> Fix IE11 support

package.json
=> Disable CSS class names minification

README.md
Hey @molefrog @rschristian! I have prepared the recipes and demos for the most common questions (debounce, popover, predefined colors, etc), but I'm kinda out of inspiration in terms of texts and README formatting in general. Could you help me here?
=> Code recipes

package.json
=> Fix CSS loading in Webpack v5

src/components/common/Interactive.tsx, tests/components.test.js
=> Fix bug when user releases cursor outside of the document bounds

README.md
Ported this awesome library for use in Angular framework
=> Updating the ports section in the README.md file

package.json
=> Fix `setNonce` type declaration publishing

package.json
Should fix #128 
Sorry, forgot to check with a publish dry run.
=> fix: Ensures .mjs files are published too

README.md
With WMR being used a bit more now I figured it makes sense to add, just in case some user of yours reads that and thinks it's not supported.
And it does work flawlessly out of the box, which is great 😁
=> docs: Adding WMR to Preact usage section

src/css/styles.css
Fixes #139
Thanks to @nikolaik for the idea.
=> Resolved rounded corner rendering bug

src/components/common/Interactive.tsx
=> Fix blur and focus behavior

README.md, demo/src/components/PickerPreview.tsx, src/components/HexColorInput.tsx, tests/components.test.js
=> Option to display "#" in `HexColorInput`

src/components/common/Interactive.tsx, tests/components.test.js
A properly rebased version of #156 
Made by @xnimorz 
https://user-images.githubusercontent.com/1178825/132987284-850713f0-0cbd-4368-8cca-a256f7f2a00b.MP4
=> Multitouch

package.json
=> Change export fields to fix Jet 28 issues
